# 빌드 이미지로 node:14 지정
FROM node:14 AS build

WORKDIR /app

# 라이브러리 설치에 필요한 파일만 복사
COPY package.json .
COPY package-lock.json .

# 외부 라이브러리 설치
RUN npm ci

# 소스코드 복사
COPY . .

# 소스코드 빌드
RUN npm run build

FROM nginx:1.21.4-alpine

# -- 추가 프록시 설정 실습
# 소스코드의 nginx.conf 파일을 이미지 빌드 시 nginx 설정으로 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
ENTRYPOINT [ "nginx" ]
CMD [ "-g", "daemon off;" ]
